import { Prisma } from "@prisma/client";

export const currencies: Prisma.CurrencyCreateInput[] = [
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    decimals: 2,
    isCrypto: false,
    isActive: true,
  },
  {
    code: "BTC",
    name: "Bitcoin",
    symbol: "₿",
    decimals: 8,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "ETH",
    name: "Ethereum",
    symbol: "Ξ",
    decimals: 18,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "USDT",
    name: "Tether USD",
    symbol: "₮",
    decimals: 6,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "SOL",
    name: "Solana",
    symbol: "◎",
    decimals: 9,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "XRP",
    name: "XRP",
    symbol: "XRP",
    decimals: 6,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "ADA",
    name: "Cardano",
    symbol: "ADA",
    decimals: 6,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "BNB",
    name: "BNB",
    symbol: "BNB",
    decimals: 18,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "AVAX",
    name: "Avalanche",
    symbol: "AVAX",
    decimals: 18,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "DOGE",
    name: "Dogecoin",
    symbol: "DOGE",
    decimals: 8,
    isCrypto: true,
    isActive: true,
  },
  {
    code: "LTC",
    name: "Litecoin",
    symbol: "Ł",
    decimals: 8,
    isCrypto: true,
    isActive: true,
  },
];